version: 2

sources:
  - name: raw
<<<<<<< HEAD
<<<<<<< HEAD
    database: le-wagon-data-atelier
=======
    database: "{{ env_var('GCP_PROJECT_ID') }}"
>>>>>>> 48eda7d2824da775670fd5dfb03b3bee3d7408c3
=======
    database: "{{ env_var('GCP_PROJECT_ID') }}"
>>>>>>> ad01f62984d1e6a5bd0a8f30719447f7621c1368
    schema: raw_dataset
    tables:
      - name: event_stats
        identifier: event_stats
        description: "Event statistics data"
        meta:
          alias: event_stats
      - name: event_timeline
        identifier: event_timeline
        description: "Event timeline data"
        meta:
          alias: event_timeline
      - name: events
        identifier: events
        description: "Events data"
        meta:
          alias: events
      - name: leagues
        identifier: leagues
        description: "Leagues data"
        meta:
          alias: leagues
      - name: players
        identifier: players
        description: "Players data"
        meta:
          alias: players
      - name: seasons
        identifier: seasons
        description: "Seasons data"
        meta:
          alias: seasons
      - name: teams
        identifier: teams
        description: "Teams data"
        meta:
          alias: teams
      - name: grandprix
        identifier: grandprix
        description: "Grand Prix data"
        meta:
          alias: grandprix
