services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=airflow
    volumes:
      - ./airflow/database/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db -U airflow || exit 1"]
      interval: 15s
      retries: 5
    ports:
      - "5433:5432"
    restart: always

  scheduler:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    command: poetry run airflow scheduler
    restart: on-failure
    depends_on:
      - postgres
      - spark-master
      - spark-worker
    healthcheck:
      test: ["CMD-SHELL", "poetry run airflow jobs check --job-type SchedulerJob --local || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DEBUG__FAIL_FAST=true
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:$POSTGRES_PASSWORD@postgres:5432/db
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__FERNET_KEY=$AIRFLOW_FERNET_KEY
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json
      - AIRFLOW_CONN_GOOGLE_CLOUD_CONNECTION=google-cloud-platform://?key_path=/app/gcp-credentials.json&scope=https://www.googleapis.com/auth/cloud-platform&project=le-wagon-data-atelier
      - PYTHONPATH=/app:$PYTHONPATH
      - DBT_HOME=/app/dbt_gameflow
      - AIRFLOW_CONN_SPARK_DEFAULT=spark://spark-master:7077
      - GCP_PROJECT_ID=le-wagon-data-atelier
    volumes:
      - ./airflow/dags:/app/airflow/dags
      - ./airflow/data:/app/airflow/data
      - ./airflow/logs:/app/airflow/logs
      - ./ingestion:/app/ingestion
      - ~/.gcp_keys/gameflow-team.json:/app/gcp-credentials.json:ro
      - ./spark_jobs:/app/spark_jobs
      - ./jars:/app/jars
      - ./dbt_gameflow:/app/dbt_gameflow
      - ./bigquery:/app/bigquery
    tty: true
    stdin_open: true

  webserver:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    command: scripts/entrypoint.sh
    restart: on-failure
    depends_on:
      - postgres
      - scheduler
      - spark-master
      - spark-worker
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:$POSTGRES_PASSWORD@postgres:5432/db
      - AIRFLOW__CORE__FERNET_KEY=$AIRFLOW_FERNET_KEY
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=airflow
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json
      - AIRFLOW_CONN_GOOGLE_CLOUD_CONNECTION=google-cloud-platform://?key_path=/app/gcp-credentials.json&scope=https://www.googleapis.com/auth/cloud-platform&project=le-wagon-data-atelier
      - PYTHONPATH=/app:$PYTHONPATH
      - DBT_HOME=/app/dbt_gameflow
      - AIRFLOW_CONN_SPARK_DEFAULT=spark://spark-master:7077
      - GCP_PROJECT_ID=le-wagon-data-atelier
    volumes:
      - ./airflow/dags:/app/airflow/dags
      - ./airflow/data:/app/airflow/data
      - ./airflow/logs:/app/airflow/logs
      - ./spark_jobs:/app/spark_jobs
      - ./ingestion:/app/ingestion
      - ./jars:/app/jars #for spark gcs connector
      - ~/.gcp_keys/gameflow-team.json:/app/gcp-credentials.json:ro
      - ./dbt_gameflow:/app/dbt_gameflow
      - ./bigquery:/app/bigquery

    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    tty: true
    stdin_open: true

  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    hostname: spark-master
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json
    volumes:
      - ./spark_jobs:/app/spark_jobs
      - ./jars:/app/jars
      - ~/.gcp_keys/gameflow-team.json:/app/gcp-credentials.json:ro
    ports:
      - "7077:7077"
      - "8081:8080"
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    hostname: spark-worker
    depends_on:
      - spark-master
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json
    volumes:
      - ./spark_jobs:/app/spark_jobs
      - ./jars:/app/jars
      - ~/.gcp_keys/gameflow-team.json:/app/gcp-credentials.json:ro
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
